### ISSUE TITLE
Error with okhttp

### ISSUE THREAD

**Issue by avikInfiflex** [langchain4j/langchain4j-examples#20]
Im getting this timeout exception when using the class "ChatWithDocumentsExamples()".  The log is as follows::
[main] dev.langchain4j.internal.RetryUtils.withRetry()
WARN: Exception was thrown on attempt 1 of 3: java.lang.RuntimeException: java.io.InterruptedIOException: timeout
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:31)
	at dev.ai4j.openai4j.RequestExecutor.execute(RequestExecutor.java:59)
	at dev.langchain4j.model.openai.OpenAiChatModel.lambda$generate$0(OpenAiChatModel.java:124)
	at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:26)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:124)
	at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:88)
	at dev.langchain4j.chain.ConversationalRetrievalChain.execute(ConversationalRetrievalChain.java:65)
	at ChatWithDocumentsExamples$IfYouNeedSimplicity.main(ChatWithDocumentsExamples.java:62)
Caused by: java.io.InterruptedIOException: timeout
	at okhttp3.internal.connection.RealCall.timeoutExit(RealCall.kt:398)
	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:360)
	at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:209)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at dev.ai4j.openai4j.SyncRequestExecutor.execute(SyncRequestExecutor.java:23)
	... 7 more

I changed the OPENAI_API_KEY to a valid one.

**Comment by langchain4j** [comment]
Hi @avikInfiflex please set a higher timeout in the model:
```java
            ChatLanguageModel chatModel = OpenAiChatModel.builder()
                    .apiKey(apiKey)
                    .timeout(Duration.ofSeconds(60))
                    .build();
```
