### ISSUE TITLE
AllMiniLmL6V2EmbeddingModel caused UnsatisfiedLinkError

### ISSUE THREAD

**Issue by gkwan-ibm** [langchain4j/langchain4j-examples#66]
I used `AllMiniLmL6V2EmbeddingModel`. It works fine first.  When I recompiled the code, my app server JVM did not need to be restarted and it picked up the recompiled class. When the code called `new AllMiniLmL6V2EmbeddingModel()`, I got `java.lang.UnsatisfiedLinkError`.

```
java.lang.UnsatisfiedLinkError: Native Library /Users/gkwan/.djl.ai/tokenizers/0.15.0-0.26.0-osx-x86_64/libtokenizers.dylib already loaded in another classloader
[INFO] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:208)
[INFO] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:181)
[INFO] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:1772)
[INFO] 	at java.base/java.lang.System.load(System.java:704)
[INFO] 	at ai.djl.huggingface.tokenizers.jni.LibUtils.loadLibrary(LibUtils.java:76)
[INFO] 	at ai.djl.huggingface.tokenizers.jni.LibUtils.<clinit>(LibUtils.java:41)
[INFO] 	at ai.djl.huggingface.tokenizers.HuggingFaceTokenizer.newInstance(HuggingFaceTokenizer.java:173)
[INFO] 	at dev.langchain4j.model.embedding.OnnxBertBiEncoder.<init>(OnnxBertBiEncoder.java:39)
[INFO] 	at dev.langchain4j.model.embedding.AbstractInProcessEmbeddingModel.loadFromJar(AbstractInProcessEmbeddingModel.java:20)
[INFO] 	at dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel.<clinit>(AllMiniLmL6V2EmbeddingModel.java:18)
[INFO] 	at dev.langchain4j.example.rest.ModelResource.similarity(ModelResource.java:131)
[INFO] 	at
```

Is there a way to avoid the reloading? Or can `AllMiniLmL6V2EmbeddingModel` and `AbstractInProcessEmbeddingModel` be improved to support my case?

**Comment by langchain4j** [comment]
@gkwan-ibm thanks a lot for reporting! Could you please [open an issue in the main repo](https://github.com/langchain4j/langchain4j/issues/new/choose) and provide all needed details to reproduce? Thank you!

**Comment by gkwan-ibm** [comment]
close
- this issue is reported at https://github.com/langchain4j/langchain4j/issues/776
